repos:
  - repo: https://github.com/psf/black
    rev: 21.5b2  # Ensure to specify the version
    hooks:
      - id: black
        name: Run black formatter

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3  # Specify the version of isort
    hooks:
      - id: isort
        name: Run isort to sort imports

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: Run flake8 for linting

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.0
    hooks:
      - id: prettier
        name: Run prettier for JS/CSS/HTML formatting

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: pytest 
        name: run full python unittest
